[Fix] Code formatting

diff --git a/etc/init.d/javamine b/etc/init.d/javamine
--- a/etc/init.d/javamine
+++ b/etc/init.d/javamine
@@ -8,7 +8,7 @@
 # processname: oom_manager.sh
 # Config file: /etc/sysconfig/javamine
 #
-# By: Adrien Mahieux - adrien.mahieux-ext@socgen.com
+# By: Adrien Mahieux - adrien.mahieux@gmail.com
 #
 #
 
@@ -47,12 +47,12 @@ _proc_ispidrunning () {
 	PID=$1
 
 	# PID Validity
-	[ -n "$PID" ] && [ "$PID" -gt "1" -a "$PID" -lt "65535" ] || {
+	[[ -n "$PID" ]] && [[ "$PID" -gt "1" ]] && [[ "$PID" -lt "65535" ]] || {
 		return 1
 	}
 
 	# Process still running
-	[ -e "/proc/$PID/cmdline" ] || {
+	[[ -e "/proc/$PID/cmdline" ]] || {
 		return 1
 	}
 
@@ -80,12 +80,12 @@ _proc_run () {
 	# Daemonise parameter is mandatory !
 	$EXEC_PATH -d $EXEC_ARGS &
 	PID=$!
-	
+
 	sleep 1
-	
+
 	# If process is not running, consider it as failed
 	_proc_ispidrunning $PID || return 1
-	
+
 	# Store the new PID
 	_proc_setpid $PID
 
@@ -100,7 +100,7 @@ _proc_setpid () {
 }
 
 _proc_getpid () {
-	[ -e "$PATH_PID" ] && {
+	[[ -e "$PATH_PID" ]] && {
 		cat $PATH_PID
 	}
 }
@@ -110,25 +110,24 @@ _install_createdir () {
 
 	DIR="$1"
 
-	[ -x "$DIR" ] || {
+	[[ -x "$DIR" ]] || {
 		mkdir -p "$DIR" || return 1
 	}
-	
 
 }
 
 start () {
-	
+
 	echo -n "Starting $EXEC_NAME ... "
 
 	# Test executable
-	[ -x "$EXEC_PATH" ] || {
+	[[ -x "$EXEC_PATH" ]] || {
 		echo -n "$EXEC_PATH not executable"
 		echo_failure
 		echo
 		return 1
 	}
-	
+
 	PID="$(_proc_getpid)"
 	# Test if process is already running
 	_proc_ispidrunning $PID  && {
@@ -137,26 +136,26 @@ start () {
 		echo
 		return 1
 	}
-	
+
 	# Try to start
 	_proc_run || {
 		echo_failure
 		echo
 		return 1
 	}
-	
+
 	echo_success
 	echo
 	return 0
 }
 
 stop () {
-	
+
 	echo -n "Stopping $EXEC_NAME ... "
 
 	# Test if process is still running
 	OPID="$(_proc_getpid)"
-	[ -z "$OPID" ] && {
+	[[ -z "$OPID" ]] && {
 		echo -n "No running manager defined"
 		echo_failure
 		echo
@@ -169,14 +168,14 @@ stop () {
 		echo
 		return 0
 	}
-	
+
 	kill $OPID || {
 		echo -n "Unable to kill PID $OPID"
 		echo_failure
 		echo
 		return 1
 	}
-	
+
 	# Remove old pid
 	_proc_setpid
 
@@ -194,45 +193,45 @@ restart () {
 status () {
 	PID="$(_proc_getpid)"
 	RPID=$(_proc_isrunning $EXEC_PATH)
-	
-	
+
+
 	# PID defined
-	[ -n "$PID" ] && {
+	if [[ -n "$PID" ]]; then
 		echo -n "Process $PID is "
-	
+
 		# running (and should)
-		_proc_ispidrunning $PID && {
+		if _proc_ispidrunning $PID; then
 			echo -n "running "
 			echo_success
 			echo
 			return 0
 		
 		# Not running (but should)
-		} || {
+		else
 			echo -n "not running"
 			echo_failure
 			echo
 			return 1
-		}
-	} || {
+		fi
+	else
 	# No PID defined
 		echo -n "No Process defined "
 		
 		# running (but shouldn't)
-		[ -n "$RPID" ] && {
+		if [[ -n "$RPID" ]]; then
 			echo -n "but process $RPID running !"
 			echo_warning
 			echo
 			return 1
-		
+
 		# not running (and shouldn't)
-		} || {
+		else
 			echo -n "and no process running"
 			echo_success
 			echo
 			return 0
-		}
-	}
+		fi
+	fi
 }
 
 zap () {
@@ -245,14 +244,14 @@ install () {
 	TMP_PATH_LOGS="$(dirname $PATH_LOGS)"
 	_install_createdir $PATH_BASE || { echo "Unable to create $PATH_BASE" ; return 1; }
 	_install_createdir $TMP_PATH_PID  || { echo "Unable to create $TMP_PATH_PID" ;  return 1; }
-	_install_createdir $TMP_PATH_LOGS || { echo "Unable to create $TMP_PATH_LOGS" ; return 1; }  
+	_install_createdir $TMP_PATH_LOGS || { echo "Unable to create $TMP_PATH_LOGS" ; return 1; }
 	
 	# Folders are available
 	return 0
 }
 
 reset () {
-	
+
 	typeset -i NBRST=0
 	for ADJFILE in /proc/*/oom_adj; do
 		grep -v 0 $ADJFILE > /dev/null && {
@@ -261,39 +260,38 @@ reset () {
 		}
 	done
 	
-	echo -n $NBRST Processes oom_adj reset to 0 
+	echo -n $NBRST Processes oom_adj reset to 0
 	echo_success
 	echo
 
 	return 0
 }
 
-case "$1" in 
-  start)  
-        start
-        ;;
-  stop)
-        stop
-        ;;
+case "$1" in
+	start)
+		start
+		;;
+	stop)
+		stop
+		;;
   restart)
-  		restart
-        ;;
-  zap)
-  		zap
+		restart
 		;;
-  status) 
-        status
-        ;;
-  reset)
-  		reset
+	zap)
+		zap
 		;;
-  install)
-  		install
+	status)
+		status
 		;;
-
-  *)
-        echo $"Usage: $0 {start|stop|zap|status|restart|reset|install}"
-        exit 1
+	reset)
+		reset
+		;;
+	install)
+		install
+		;;
+	*)
+		echo $"Usage: $0 {start|stop|zap|status|restart|reset|install}"
+		exit 1
 		;;
 esac
 
